---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: soft123
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

